### ISSUE TITLE
cargo build --release error using master branch

### ISSUE THREAD

**Issue by stardustman** [vbrandl/bind9-api#103]
Compiling rand v0.5.6
   Compiling socket2 v0.3.9
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
   --> /Users/my/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/socket2-0.3.9/src/sockaddr.rs:153:9
    |
153 |         mem::transmute::<SocketAddrV4, sockaddr_in>(v4);
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: source type: `SocketAddrV4` (48 bits)
    = note: target type: `sockaddr_in` (128 bits)

   Compiling miniz_oxide_c_api v0.2.1
For more information about this error, try `rustc --explain E0512`.
error: could not compile `socket2` (lib) due to previous error

**Comment by vbrandl** [comment]
The problem seems to be a old and yanked version of the `socket2` crate. I just updated the dependencies and pushed the change. After pulling the current `master`, you should be able to build the project

**Comment by stardustman** [comment]
> The problem seems to be a old and yanked version of the `socket2` crate. I just updated the dependencies and pushed the change. After pulling the current `master`, you should be able to build the project

yes, it works.
